### ISSUE TITLE
Chatper 02 - GNS3 Set Up

### ISSUE THREAD

**Issue by jeantardelli** [PacktPublishing/Mastering-Python-Networking-Third-Edition#13]
Hi Eric,

How are you?

This isn't actually an issue, I would like to ask you if is it possible to include a GNS3 configuration as well as how to talk to pexpect in this chapter.

Thank you very much for the book.

**Comment by ericchou1** [comment]
Hi Jean, we only need ip reachability to the management IP for the devices for the scripts to run. So it is certainly possible to use GNS3 as long as you can source your own Cisco IOS, NX-OS, or IOS-XE images. For vendors such as Arista / Vyetta / Juniper they have their own virtualization platform VM that can be reached from GNS3 lab, but you can also choose to run them individually. 

Hope it helps, 

Eric

**Comment by jeantardelli** [comment]
Hi, Eric. It worked here, I was forgetting to manage the physical connection between GNS3 and Ubuntu.  :)
Thanks again.
